### ISSUE TITLE
Enhancement: Accept data from request body

### ISSUE THREAD

**Issue by curusarn** [ufal/nametag#9]
Currently, data has to be sent as part of the URL.  
Which is not ideal because nametag comfortably handles large requests (thousands of characters) but it is not standard to use URLs longer than a few thousands of characters.  

I propose to accept data from request body instead or in addition to accepting data from URL.

**Comment by foxik** [comment]
This actually works since the beginning -- the data can be sent using POST request in the request body, either using `application/x-www-form-urlencoded` or `mulitpart/formdata` encoding.

You can test it easily using for example curl and `-F`, which constructs POST request with `multipart/formdata` encoding ([see the documentation](http://lindat.mff.cuni.cz/services/nametag/api-reference.php#using_curl)):
```
curl -F 'data="Vltava"' -F output=vertical http://lindat.mff.cuni.cz/services/nametag/api/recognize
```
